# Generated by Django 4.2.7 on 2025-04-04 12:12

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import addon_service.configured_addon.link.models
import addon_service.external_service.link.models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0011_oauth2tokenmetadata_date_last_refreshed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizedLinkAccount",
            fields=[
                (
                    "authorizedaccount_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addon_service.authorizedaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authorized Link Account",
                "verbose_name_plural": "Authorized Link Accounts",
            },
            bases=("addon_service.authorizedaccount",),
        ),
        migrations.CreateModel(
            name="ConfiguredLinkAddon",
            fields=[
                (
                    "configuredaddon_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addon_service.configuredaddon",
                    ),
                ),
                ("target_id", models.CharField()),
                (
                    "int_resource_type",
                    models.BigIntegerField(
                        validators=[
                            addon_service.configured_addon.link.models.is_supported_resource_type
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Configured Link Addon",
                "verbose_name_plural": "Configured Link Addons",
            },
            bases=("addon_service.configuredaddon",),
        ),
        migrations.CreateModel(
            name="ExternalLinkService",
            fields=[
                (
                    "externalservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addon_service.externalservice",
                    ),
                ),
                (
                    "int_supported_resource_types",
                    models.BigIntegerField(
                        null=True,
                        validators=[
                            addon_service.external_service.link.models.validate_supported_features
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "External Link Service",
                "verbose_name_plural": "External Link Services",
            },
            bases=("addon_service.externalservice",),
        ),
    ]
