# Generated by Django 4.2.7 on 2025-03-11 17:44

import addon_service.external_service.link.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addon_service', '0011_oauth2tokenmetadata_date_last_refreshed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedLinkAccount',
            fields=[
                ('authorizedaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='addon_service.authorizedaccount')),
                ('default_root_folder', models.CharField(blank=True)),
            ],
            options={
                'verbose_name': 'Authorized Link Account',
                'verbose_name_plural': 'Authorized Link Accounts',
            },
            bases=('addon_service.authorizedaccount',),
        ),
        migrations.CreateModel(
            name='ConfiguredLinkAddon',
            fields=[
                ('configuredaddon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='addon_service.configuredaddon')),
                ('root_folder', models.CharField(blank=True)),
            ],
            options={
                'verbose_name': 'Configured Link Addon',
                'verbose_name_plural': 'Configured Link Addons',
            },
            bases=('addon_service.configuredaddon',),
        ),
        migrations.CreateModel(
            name='ExternalLinkService',
            fields=[
                ('externalservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='addon_service.externalservice')),
                ('max_concurrent_downloads', models.IntegerField()),
                ('max_upload_mb', models.IntegerField()),
                ('int_supported_features', models.IntegerField(null=True, validators=[addon_service.external_service.link.models.validate_supported_features])),
            ],
            options={
                'verbose_name': 'External Link Service',
                'verbose_name_plural': 'External Link Services',
            },
            bases=('addon_service.externalservice',),
        ),
    ]
