# Generated by Django 4.2.7 on 2025-03-04 15:30

from django.db import (
    migrations,
    models,
)

import addon_service.common.validators
from addon_service.credentials.models import ExternalCredentials


def migrate_credential_format(*args, **kwargs):
    skipped = 0
    processed = 0
    for credential in ExternalCredentials.objects.iterator():
        if creds_format := credential.format:
            credential.int_credentials_format = creds_format.value
            credential.save()
            processed += 1
        else:
            skipped += 1
    print(f"\nMigrating credential format: {skipped=}, {processed=}")


class Migration(migrations.Migration):
    dependencies = [
        ("addon_service", "0012_alter_authorizedaccount__credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcredentials",
            name="int_credentials_format",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    addon_service.common.validators.validate_credentials_format
                ],
                verbose_name="Credentials format",
            ),
        ),
        migrations.RunPython(migrate_credential_format),
    ]
