# Generated by Django 4.2.7 on 2025-04-03 10:10

from django.db import (
    migrations,
    models,
)

import addon_service.configured_addon.link.models
import addon_service.external_service.link.models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0012_authorizedlinkaccount_configuredlinkaddon_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externallinkservice",
            options={
                "verbose_name": "External Link Service",
                "verbose_name_plural": "External Link Services",
            },
        ),
        migrations.RemoveField(
            model_name="configuredlinkaddon",
            name="target_uri",
        ),
        migrations.AlterField(
            model_name="configuredlinkaddon",
            name="int_resource_type",
            field=models.IntegerField(
                validators=[
                    addon_service.configured_addon.link.models.is_supported_resource_type
                ]
            ),
        ),
        migrations.AlterField(
            model_name="externallinkservice",
            name="int_supported_resource_types",
            field=models.BigIntegerField(
                null=True,
                validators=[
                    addon_service.external_service.link.models.validate_supported_features
                ],
            ),
        ),
    ]
