# Generated by Django 4.2.7 on 2025-03-04 15:30

from django.db import (
    migrations,
    models,
)

import addon_service.common.validators
from addon_service.credentials.models import ExternalCredentials
from addon_service.external_service.models import ExternalService


def migrate_credential_format(*args, **kwargs):
    for service in ExternalService.objects.all():
        ExternalCredentials.objects.filter(
            authorized_account__external_service=service
        ).update(int_credentials_format=service.credentials_format)


class Migration(migrations.Migration):
    dependencies = [
        ("addon_service", "0012_alter_authorizedaccount__credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcredentials",
            name="int_credentials_format",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    addon_service.common.validators.validate_credentials_format
                ],
                verbose_name="Credentials format",
            ),
        ),
        migrations.RunPython(migrate_credential_format),
    ]
