# Generated by Django 4.2.7 on 2025-04-17 16:44

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0012_authorizedlinkaccount_configuredlinkaddon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallinkservice",
            name="browser_base_url",
            field=models.URLField(blank=True, default=""),
        )
    ]
