# Generated by Django 4.2.7 on 2025-05-05 20:22

from django.db import (
    migrations,
    models,
)

import addon_service.configured_addon.link.models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0014_authorizedlinkaccount_configuredlinkaddon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuredlinkaddon",
            name="int_resource_type",
            field=models.BigIntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    addon_service.configured_addon.link.models.is_supported_resource_type
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configuredlinkaddon",
            name="target_id",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
