# Generated by Django 4.2.20 on 2025-05-27 13:57

from django.db import (
    migrations,
    models,
)

import addon_service.external_service.link.models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0015_alter_configuredlinkaddon_int_resource_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallinkservice",
            name="int_supported_features",
            field=models.IntegerField(
                null=True,
                validators=[
                    addon_service.external_service.link.models.validate_supported_features
                ],
            ),
        ),
        migrations.AlterField(
            model_name="externallinkservice",
            name="int_supported_resource_types",
            field=models.BigIntegerField(
                null=True,
                validators=[
                    addon_service.external_service.link.models.validate_supported_resource_types
                ],
            ),
        ),
    ]
