# Generated by Django 4.2.20 on 2025-09-11 18:14

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0016_externallinkservice_int_supported_features_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRedirectService",
            fields=[
                (
                    "externalservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addon_service.externalservice",
                    ),
                ),
                ("redirect_url", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name": "External Redirect Service",
                "verbose_name_plural": "External Redirect Services",
            },
            bases=("addon_service.externalservice",),
        ),
    ]
